common:
    # lid_topic:  "/points_raw"
    lid_topic:  "/rslidar_points"
    imu_topic:  "/camera/imu"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 4               # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    blind: 4

mapping:
    acc_cov: 0.01608843085721201
    gyr_cov: 0.0017892995284273933
    b_acc_cov: 0.00035756256498712546
    b_gyr_cov: 1.5882455476866487e-05
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0.0199, -0.19898, -0.09914]
    extrinsic_R: [ 0.17594, -0.98396, -0.02931, 
                   -0.01550, 0.027, -0.99952, 
                   0.98429, 0.17628, -0.0105]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.