common:
    # lid_topic:  "/points_raw"
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu/data"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 32
    blind: 4

mapping:
    acc_cov: 0.01608843085721201
    gyr_cov: 0.0017892995284273933
    b_acc_cov: 0.00035756256498712546
    b_gyr_cov: 1.5882455476866487e-05
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
    # T that transforms imu coor. to lidar coor. OR how imu frame expressed in lidar frame
    # R that rotates lidar frame to imu frame;
    # t that moves lidar frame to imu frame expressed in lidar frame
    extrinsic_T: [ 0.5158, -1.3906, -1.4998]
    extrinsic_R: [ 0.99163, -0.020025, -0.12759, 0.0046427, 0.99279, -0.11974, 0.12907, 0.11814, 0.98457]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
    runtime_pos_log: true
pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.